norm:
  PUJetID:
    expression: weight_Jet_PUJetID_eff{scale}_rel_b1_2 * weight_Jet_PUJetID_eff{scale}_rel_b2_2 * final_weight
  PileUp_Lumi_MC:
    expression: weight_MC_Lumi_pu{scale}_rel  * final_weight
  L1Prefiring:
    expression: weight_L1PreFiring{scale}_rel  * final_weight
  # L1Prefiring_ECAL:
    # expression: weight_L1PreFiring_ECAL{scale}_rel * final_weight
  # L1Prefiring_Muon_Stat:
    # expression: weight_L1PreFiring_Muon_Stat{scale}_rel * final_weight
  # L1Prefiring_Muon_Syst:
    # expression: weight_L1PreFiring_Muon_Syst{scale}_rel * final_weight
  pNet_SF:
    expression: weight_pNet_{scale}_rel * final_weight
  bTagShape_lf:
    expression: weight_bTagShape_lf{scale}_rel * final_weight
    requires_btag: False
  bTagShape_hf:
    expression: weight_bTagShape_hf{scale}_rel * final_weight
    requires_btag: False
  bTagShape_lfstats1:
    expression: weight_bTagShape_lfstats1{scale}_rel * final_weight
    requires_btag: False
  bTagShape_lfstats2:
    expression: weight_bTagShape_lfstats2{scale}_rel * final_weight
    requires_btag: False
  bTagShape_hfstats1:
    expression: weight_bTagShape_hfstats1{scale}_rel * final_weight
    requires_btag: False
  bTagShape_hfstats2:
    expression: weight_bTagShape_hfstats2{scale}_rel * final_weight
    requires_btag: False
  bTagShape_cferr1:
    expression: weight_bTagShape_cferr1{scale}_rel * final_weight
    requires_btag: False
  bTagShape_cferr2:
    expression: weight_bTagShape_cferr2{scale}_rel * final_weight
    requires_btag: False

  TauID_total:
    expression: weight_tau1_TauID_SF_Medium_total{scale}_rel * weight_tau2_TauID_SF_Medium_total{scale}_rel * final_weight
  TauID_stat1_DM0:
    expression: weight_tau1_TauID_SF_Medium_stat1_dm0{scale}_rel * weight_tau2_TauID_SF_Medium_stat1_dm0{scale}_rel * final_weight
  TauID_stat1_DM10:
    expression: weight_tau1_TauID_SF_Medium_stat1_dm10{scale}_rel * weight_tau2_TauID_SF_Medium_stat1_dm10{scale}_rel * final_weight
  TauID_stat1_DM11:
    expression: weight_tau1_TauID_SF_Medium_stat1_dm11{scale}_rel * weight_tau2_TauID_SF_Medium_stat1_dm11{scale}_rel * final_weight
  TauID_stat1_DM1:
    expression: weight_tau1_TauID_SF_Medium_stat1_dm1{scale}_rel * weight_tau2_TauID_SF_Medium_stat1_dm1{scale}_rel * final_weight
  TauID_stat2_DM0:
    expression: weight_tau1_TauID_SF_Medium_stat2_dm0{scale}_rel * weight_tau2_TauID_SF_Medium_stat2_dm0{scale}_rel * final_weight
  TauID_stat2_DM10:
    expression: weight_tau1_TauID_SF_Medium_stat2_dm10{scale}_rel * weight_tau2_TauID_SF_Medium_stat2_dm10{scale}_rel * final_weight
  TauID_stat2_DM11:
    expression: weight_tau1_TauID_SF_Medium_stat2_dm11{scale}_rel * weight_tau2_TauID_SF_Medium_stat2_dm11{scale}_rel * final_weight
  TauID_stat2_DM1:
    expression: weight_tau1_TauID_SF_Medium_stat2_dm1{scale}_rel * weight_tau2_TauID_SF_Medium_stat2_dm1{scale}_rel * final_weight
  TauID_syst_alleras:
    expression: weight_tau1_TauID_SF_Medium_syst_alleras{scale}_rel * weight_tau2_TauID_SF_Medium_syst_alleras{scale}_rel * final_weight
  TauID_syst_year:
    expression: weight_tau1_TauID_SF_Medium_syst_year{scale}_rel * weight_tau2_TauID_SF_Medium_syst_year{scale}_rel * final_weight
  TauID_syst_year_DM0:
    expression: weight_tau1_TauID_SF_Medium_syst_year_dm0{scale}_rel * weight_tau2_TauID_SF_Medium_syst_year_dm0{scale}_rel * final_weight
  TauID_syst_year_DM10:
    expression: weight_tau1_TauID_SF_Medium_syst_year_dm10{scale}_rel * weight_tau2_TauID_SF_Medium_syst_year_dm10{scale}_rel * final_weight
  TauID_syst_year_DM11:
    expression: weight_tau1_TauID_SF_Medium_syst_year_dm11{scale}_rel * weight_tau2_TauID_SF_Medium_syst_year_dm11{scale}_rel * final_weight
  TauID_syst_year_DM1:
    expression: weight_tau1_TauID_SF_Medium_syst_year_dm1{scale}_rel * weight_tau2_TauID_SF_Medium_syst_year_dm1{scale}_rel * final_weight
  TauID_genuineElectron_barrel:
    expression: weight_tau1_TauID_SF_Medium_genuineElectron_barrel{scale}_rel * weight_tau2_TauID_SF_Medium_genuineElectron_barrel{scale}_rel * final_weight
  TauID_genuineElectron_endcaps:
    expression: weight_tau1_TauID_SF_Medium_genuineElectron_endcaps{scale}_rel * weight_tau2_TauID_SF_Medium_genuineElectron_endcaps{scale}_rel * final_weight
  TauID_genuineMuon_eta0p4to0p8:
    expression: weight_tau1_TauID_SF_Medium_genuineMuon_eta0p4to0p8{scale}_rel * weight_tau2_TauID_SF_Medium_genuineMuon_eta0p4to0p8{scale}_rel * final_weight
  TauID_genuineMuon_eta0p8to1p2:
    expression: weight_tau1_TauID_SF_Medium_genuineMuon_eta0p8to1p2{scale}_rel * weight_tau2_TauID_SF_Medium_genuineMuon_eta0p8to1p2{scale}_rel * final_weight
  TauID_genuineMuon_eta1p2to1p7:
    expression: weight_tau1_TauID_SF_Medium_genuineMuon_eta1p2to1p7{scale}_rel * weight_tau2_TauID_SF_Medium_genuineMuon_eta1p2to1p7{scale}_rel * final_weight
  TauID_genuineMuon_etaGt1p7:
    expression: weight_tau1_TauID_SF_Medium_genuineMuon_etaGt1p7{scale}_rel * weight_tau2_TauID_SF_Medium_genuineMuon_etaGt1p7{scale}_rel * final_weight
  TauID_genuineMuon_etaLt0p4:
    expression: weight_tau1_TauID_SF_Medium_genuineMuon_etaLt0p4{scale}_rel * weight_tau2_TauID_SF_Medium_genuineMuon_etaLt0p4{scale}_rel * final_weight
  TauID_SF_stat_highpT_bin1:
    expression: weight_tau1_TauID_SF_Medium_stat_highpT_bin1{scale}_rel * weight_tau2_TauID_SF_Medium_stat_highpT_bin1{scale}_rel * final_weight
  TauID_SF_stat_highpT_bin2:
    expression: weight_tau1_TauID_SF_Medium_stat_highpT_bin2{scale}_rel * weight_tau2_TauID_SF_Medium_stat_highpT_bin2{scale}_rel * final_weight
  TauID_SF_syst_highpT_bin1:
    expression: weight_tau1_TauID_SF_Medium_syst_highpT_bin1{scale}_rel * weight_tau2_TauID_SF_Medium_syst_highpT_bin1{scale}_rel * final_weight
  TauID_SF_syst_highpT_bin2:
    expression: weight_tau1_TauID_SF_Medium_syst_highpT_bin2{scale}_rel * weight_tau2_TauID_SF_Medium_syst_highpT_bin2{scale}_rel * final_weight
  TauID_SF_syst_highpT_extrap:
    expression: weight_tau1_TauID_SF_Medium_syst_highpT_extrap{scale}_rel * weight_tau2_TauID_SF_Medium_syst_highpT_extrap{scale}_rel * final_weight
  EleID_Iso:
    expression: weight_tau1_EleSF_wp80iso_EleID{scale}_rel * final_weight # in all channels is the first leg
  EleIS_noIso:
    expression: weight_tau1_EleSF_wp80noiso_EleID{scale}_rel * final_weight # only for eE, it's the second ele
  # muId weights not valid for eMu because it should be the second leg only
  MuID_Reco_highPt:
    expression: weight_tau1_HighPt_MuonID_SF_Reco{scale}_rel * weight_tau2_HighPt_MuonID_SF_Reco{scale}_rel *final_weight
  MuID_TightID_highPt:
    expression: weight_tau1_HighPt_MuonID_SF_TightID{scale}_rel * weight_tau2_HighPt_MuonID_SF_TightID{scale}_rel *final_weight
  MuID_Reco:
    expression: weight_tau1_MuonID_SF_Reco{scale}_rel * weight_tau2_MuonID_SF_Reco{scale}_rel *final_weight
  MuID_TightID:
     expression: weight_tau1_MuonID_SF_TightID_Trk{scale}_rel * weight_tau2_MuonID_SF_TightID_Trk{scale}_rel *final_weight
  MuID_TightRelIso:
    expression: weight_tau1_MuonID_SF_TightRelIso{scale}_rel * weight_tau2_MuonID_SF_TightRelIso{scale}_rel * final_weight

  HLT_MET:
    expression: weight_TrgSF_MET{scale}_rel * final_weight

  HLT_ditau_DM0:
    expression: weight_HLT_ditau_DM0{scale}_rel * final_weight
  HLT_ditau_DM1:
    expression: weight_HLT_ditau_DM1{scale}_rel * final_weight
  HLT_ditau_3Prong:
    expression: weight_HLT_ditau_3Prong{scale}_rel * final_weight
  HLT_singleTau:
    expression: weight_HLT_singleTau_{scale}_rel  * final_weight
  HLT_singleEle:
    expression: weight_HLT_singleEle{scale}_rel * final_weight
  HLT_singleMu:
    expression: weight_HLT_singleMu{scale}_rel * final_weight
  HLT_eMu:
    expression: weight_HLT_eMu{scale}_rel * final_weight
  weight_trigSF_cross_ele:
    expression: (weight_trigSF_cross_ele_{scale}/weight_HLT_eTau) * final_weight
  weight_trigSF_SL_ele:
    expression: (weight_trigSF_SL_ele_{scale}/weight_HLT_eTau) * final_weight
  weight_trigSF_ele:
    expression: (weight_trigSF_ele_{scale}/weight_HLT_eTau) * final_weight
  weight_trigSF_etau_tau:
    expression: (weight_trigSF_etau_tau_{scale}/weight_HLT_eTau) * final_weight
  weight_trigSF_cross_mu:
    expression: (weight_trigSF_cross_mu_{scale}/weight_HLT_muTau) * final_weight
  weight_trigSF_SL_mu:
    expression: (weight_trigSF_SL_mu_{scale}/weight_HLT_muTau) * final_weight
  weight_trigSF_mu:
    expression: (weight_trigSF_mu_{scale}/weight_HLT_muTau) * final_weight
  weight_trigSF_mutau_tau:
    expression: (weight_trigSF_mutau_tau_{scale}/weight_HLT_muTau) * final_weight


shape:
  - TauES_DM0
  - TauES_DM1
  - TauES_3prong
  - EleFakingTauES_DM0
  - EleFakingTauES_DM1
  - MuFakingTauES
  - JER
  - JES_FlavorQCD
  - JES_RelativeBal
  - JES_HF
  - JES_BBEC1
  - JES_EC2
  - JES_Absolute
  - JES_BBEC1_2017
  - JES_Absolute_2017
  - JES_EC2_2017
  - JES_HF_2017
  - JES_RelativeSample_2017
  - QCDScale
