analysis: hh_bbtautau
# type: resonant or nonresonant, set as needed
# model: ... (fill in as needed for your analysis)
model:
  parameters: [ MX ]
  param_dependent_bkg: false
  input_file_pattern: dnn_M0_Signal/dnn_M0_Signal.root
hist_bins: [ 0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 1 ]
signalFractionForRelevantBins: 0.2

eras:
  - Run3_2022EE
channels:
  - muTau
  - eTau
  - tauTau
categories:
  - inclusive
  # Add more categories as needed
processes:
  - process: data_obs
    is_data: true
    is_asimov_data: true
  - process: GluGlutoRadiontoHHto2B2Tau2Nu_M_${MX}
    hist_name: GluGlutoRadiontoHHto2B2Tau2Nu_M_${MX}
    param_values: [ 250, 260, 270, 280, 300, 350, 450, 550, 600, 650, 700, 800 ]
    is_signal: true
    # scale: ... (add if needed)
  - TT
  - DY
  - VV
  - ST
  - QCD
uncertainties:
  - name: lumi_13p6TeV
    type: lnN
    value: 0.014
  - name: MuonID
    type: shape
  - name: EleID
    type: shape
  - name: TauID
    type: shape
  - name: SingleMuonTrg
    type: shape
  - name: SingleEleTrg
    type: shape
  - name: CMS_pileup_2022EE
    type: shape
    eras:
    - Run3_2022EE
  - name: JER
    type: shape
  - name: EleES
    type: shape
  - name: QCD_shape
    type: shape
    processes: [QCD]
  - name: QCD_scale_TT
    type: lnN
    processes:
    - TT
    value: [ -0.036, 0.025 ]
  - name: QCD_scale_DY
    type: lnN
    processes:
    - DY
    value: [ -0.011, 0.007 ]
  - name: QCD_scale_ST
    type: lnN
    processes:
    - ST
    value: [ -0.022, +0.022 ]
  - name: QCD_scale_VV
    type: lnN
    processes:
    - VV
    value: 0.005
  - name: PDF_alphas
    hasMultipleValues: True
    type: lnN
    value:
    - value: 0.025
      type: lnN
      processes:
      - TT
    - value: 0.01
      type: lnN
      processes:
      - DY
    - value: 0.027
      type: lnN
      processes:
      - ST
  - name: top_mass
    hasMultipleValues: True
    type: lnN
    value: 
    - value: [ -0.027, 0.028 ]
      type: lnN
      processes: 
      - TT
    - value: [ -0.015, 0.015 ]
      type: lnN
      processes:
      - ST
autolnNThr: 0.1
asymlnNThr: 0.001
ignorelnNThr: 0.001
autoMCStats:
  apply: true
  threshold: 20
  apply_to_signal: true
  mode: 1 